SCREEN_HEIGHT = 600
# SCREEN_WIDTH = 800
SCREEN_WIDTH = SCREEN_HEIGHT * 9/16
FPS = 60

# Define the number of lanes
LANE_COUNT = 2
LANE_WIDTH = SCREEN_WIDTH // LANE_COUNT

BG_SPEED = 0.5
ENEMY_SPEED = 1
ENTITY_SPEED = 2

INIT_HEALTH = 5
INIT_SHOOT_INTERVAL = 250